### ISSUE TITLE
TypeError on Windows

### ISSUE THREAD

**Issue by fischerman** [yuanchuan/markdown-preview#5]
I get the following error when I try to run markdown-preview
```
C:\Users\Name\Documents\mips-rsa>markdown-preview README.md

C:\Users\Name\AppData\Roaming\npm\node_modules\markdown-preview\lib\parser.js:9
var converter = new showdown.converter();
                ^
TypeError: undefined is not a function
    at Object.<anonymous> (C:\Users\Name\AppData\Roaming\npm\node_modules\markdown-preview\lib\parser.js:9:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Name\AppData\Roaming\npm\node_modules\markdown-preview\lib\server.js:13:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```
I use Windows 8.1 x64
The installation appears to work fine
```
C:\Users\Name>npm install -g markdown-preview
npm http GET https://registry.npmjs.org/markdown-preview
npm http 304 https://registry.npmjs.org/markdown-preview
npm http GET https://registry.npmjs.org/open
npm http GET https://registry.npmjs.org/node-watch
npm http GET https://registry.npmjs.org/showdown
npm http GET https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/node-watch
npm http 304 https://registry.npmjs.org/showdown
npm http 304 https://registry.npmjs.org/open
C:\Users\Name\AppData\Roaming\npm\markdown-preview -> C:\Users\Name\AppData\Roaming\npm\node_modules\markdown-preview\bin\markd
own-preview
markdown-preview@0.2.7 C:\Users\Name\AppData\Roaming\npm\node_modules\markdown-preview
├── node-watch@0.3.4
├── open@0.0.5
├── mime@1.3.4
└── showdown@1.0.0-alpha.2
```

**Comment by yuanchuan** [comment]
Just published a new version and fixed the package. Please check it out.
